###
POST http://localhost:8080/api/book
Content-Type: application/json

{
  "bookName": "Book 1",
  "author": "Author 1",
  "price": 10
}

###

GET http://localhost:8080/api/book/1

###

GET http://localhost:8080/api/book

